Added linter.yml files into the feature branch
lucy-sees/Hello-Microverse-project pull request #1
Opened 2023-04-25 09:27 UTC by lucy-sees

first pull request you should see the result of the GitHub actions checks

2023-04-27 15:05 UTC, usorfaitheloho requested changes

2023-04-27 15:05 UTC, usorfaitheloho commented on README.md
> +- [👥 Authors](#authors)
According to the recommended Microverse README template given to students, there is an `Installation` and `Future features` section of the file and the only optional section is the  `FAQ` section . Please kindly add these sections back in your README file with the required contents for them 😄

2023-04-27 15:23 UTC, usorfaitheloho requested changes
## Hi @lucy-sees   :clap:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif)

## To Highlight :clap:  
:arrow_forward: Git/Github flow best practices has been followed :heavy_check_mark: 
:arrow_forward: Good code quality :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- Please use more descriptive branch names for your projects to enable reviewers understand the exact feature that was introduced in your PR 😄 
 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 12:08 UTC, wayungi requested changes
Hi @lucy-sees , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] All linter checks are passing ✔️ 
- [ ] Atomic commit messages ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body ✔️ 

## Required Changes ♻️
_Check the comments under the review._
- [ ] Your feature branch name is not descriptive. Please checkout to a new branch and use the correct name and mention the old PR in the new PR. A good branch name describes what features the branch has. ie **hello_microverse-setup**
![branch](https://user-images.githubusercontent.com/99656687/236622781-9f871acd-a0da-4f07-84dc-508977fb0a9e.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 12:08 UTC, wayungi commented on test.md
- [ ] Please delete this file from your repo since it is gitignored and should not be in the repo 👍🏾 
![inst](https://user-images.githubusercontent.com/99656687/236623031-9e0d1dac-047c-48ed-a28e-8f2ca2052b87.png)

2023-05-06 18:58 UTC, closed without merging